spring:
  datasource:
    url: jdbc:mysql://prod-db-host:3306/prod_database
    driverClassName: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
